# Permission constants
VIEW_DASHBOARD = "VIEW_DASHBOARD"
VIEW_PRODUCTS = "VIEW_PRODUCTS"
MANAGE_PRODUCTS = "MANAGE_PRODUCTS"
VIEW_CATEGORIES = "VIEW_CATEGORIES"
MANAGE_CATEGORIES = "MANAGE_CATEGORIES"
VIEW_INVENTORY = "VIEW_INVENTORY"
ADJUST_STOCK = "ADJUST_STOCK"
ACCESS_SALES = "ACCESS_SALES"
VIEW_SALES_HISTORY = "VIEW_SALES_HISTORY"
RECORD_EXPENSES = "RECORD_EXPENSES"
VIEW_REPORTS = "VIEW_REPORTS"
EXPORT_REPORTS = "EXPORT_REPORTS"
MANAGE_SETTINGS = "MANAGE_SETTINGS"
MANAGE_USERS = "MANAGE_USERS"
CREATE_BACKUP = "CREATE_BACKUP"

# Role permission mappings
ROLE_PERMISSIONS = {
    "owner": {
        VIEW_DASHBOARD,
        VIEW_PRODUCTS,
        MANAGE_PRODUCTS,
        VIEW_CATEGORIES,
        MANAGE_CATEGORIES,
        VIEW_INVENTORY,
        ADJUST_STOCK,
        ACCESS_SALES,
        VIEW_SALES_HISTORY,
        RECORD_EXPENSES,
        VIEW_REPORTS,
        EXPORT_REPORTS,
        MANAGE_SETTINGS,
        MANAGE_USERS,
        CREATE_BACKUP,
    },
    "cashier": {
        ACCESS_SALES,
        VIEW_PRODUCTS,
        VIEW_SALES_HISTORY,
    },
    "inventory_manager": {
        VIEW_PRODUCTS,
        MANAGE_PRODUCTS,
        VIEW_CATEGORIES,
        MANAGE_CATEGORIES,
        VIEW_INVENTORY,
        ADJUST_STOCK,
        VIEW_REPORTS,
    },
    "accountant": {
        VIEW_DASHBOARD,
        VIEW_SALES_HISTORY,
        RECORD_EXPENSES,
        VIEW_REPORTS,
        EXPORT_REPORTS,
    },
}
